maintenance:
  message: |
    §7-------------------- §aClearSMP §7--------------------

    §cThis server is currently offline.
    §7Please contact the server administrator and ask them to bring it online.

    §7Powered by §eReplit.
    §bClearSMP.github.io
